############################
########## CONFIG ##########
spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_SERVER}:${KEYCLOAK_PORT}/realms/mscourserealm

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://cursoms-eureka-user:akre-rcusmueruoe-ss@${EUREKA_SERVER}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log
